### ISSUE TITLE
The speed is super low

### ISSUE THREAD

**Issue by vasiledoe** [vividos/UsbOtgFileReader#1]
If we wanna copy files from USB to local storage "Download" option in your app, then speed is super low if we compare with other apps from Google Play like  "File Manager +" or "USB OTG File Manager". I also have an app that uses this [libaums](https://github.com/magnusja/libaums) and I have the same issue. Do you have any clue how this can be improved?

**Comment by vasiledoe** [comment]
** you can try with a video that has for example 500+ MB to see it better

**Comment by vividos** [comment]
I'm just using the libaums library, so the issue most probably is here.
Also if you have a newer Android phone, USB OTG support should just work, I only had issues and created this app because my Android 8.1 smartphone didn't support this yet.
